import { useState, useRef, useEffect, useMemo } from 'react';
import ReactMarkdown from 'react-markdown';
import { useDatabase } from '../../context/DatabaseContext';
import { useUser } from '../../context/UserContext';
import { getRoleLabel } from '../../config/roleAccess';
import type { ChatMessage, ChatCard, ChatAction, MeasurementPreview, Visit, Measurement } from '../../types';
import type { Entry } from '../PlanBuilder/planData';
import { queryAI } from '../../services/aiService';
import type { BudgetSuggestion, AnomalyReport, GeneratedReport, FieldNotesResult } from '../../services/aiService';
import { useChat } from '../../context/ChatContext';

/* ---- PDF Export ---- */

function exportReportToPdf(report: GeneratedReport) {
  const win = window.open('', '_blank');
  if (!win) return;
  const html = `<!DOCTYPE html>
<html><head><meta charset="utf-8"><title>${report.title}</title>
<style>
body{font-family:'Segoe UI',system-ui,sans-serif;max-width:700px;margin:40px auto;padding:0 20px;color:#1a1c1e;line-height:1.6}
h1{font-size:22px;border-bottom:2px solid #378ADD;padding-bottom:8px;margin-bottom:4px}
.period{font-size:13px;color:#6b7280;margin-bottom:20px}
.reliability{font-size:11px;color:#6b7280;margin-bottom:16px}
.metrics{display:flex;gap:12px;margin-bottom:24px;flex-wrap:wrap}
.metric{padding:12px 16px;background:#f4f5f7;border-radius:8px;min-width:100px}
.metric-label{font-size:10px;color:#9ca3af;text-transform:uppercase;letter-spacing:0.3px}
.metric-val{font-size:20px;font-weight:600}
h2{font-size:15px;margin:20px 0 6px;color:#1a1c1e}
p{font-size:13px;color:#374151;margin:0 0 12px}
.footer{margin-top:32px;padding-top:12px;border-top:1px solid #e5e7eb;font-size:10px;color:#9ca3af;text-align:center}
@media print{body{margin:20px}}
</style></head><body>
<h1>${report.title}</h1>
<div class="period">${report.period}</div>
<div class="reliability">AI Reliability Score: ${report.reliability ?? '—'}%</div>
${report.metrics && Object.keys(report.metrics).length > 0 ? `<div class="metrics">${Object.entries(report.metrics).map(([k, v]) => `<div class="metric"><div class="metric-label">${k}</div><div class="metric-val">${v}</div></div>`).join('')}</div>` : ''}
${report.sections.map(s => `<h2>${s.heading}</h2><p>${s.content}</p>`).join('')}
<div class="footer">Generated by EcoPlanner AI | ARSO Environmental Monitoring | ${new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })}</div>
</body></html>`;
  win.document.write(html);
  win.document.close();
  setTimeout(() => win.print(), 300);
}

/* ---- Reliability Badge ---- */

function ReliabilityBadge({ score }: { score?: number }) {
  if (score === undefined || score === null) return null;
  const color = score >= 90 ? '#639922' : score >= 70 ? '#378ADD' : score >= 50 ? '#EF9F27' : '#E24B4A';
  const label = score >= 90 ? 'High' : score >= 70 ? 'Good' : score >= 50 ? 'Fair' : 'Low';
  return (
    <span className="ai-reliability" style={{ color, borderColor: color + '44' }} title={`AI confidence: ${score}%`}>
      {score}% {label}
    </span>
  );
}

/* ---- Dynamic measurement suggestion ---- */

const MEASUREMENT_TYPES = ['Basic Chemistry', 'Heavy Metals', 'Biological Assessment', 'Microplastics', 'Nutrient Analysis', 'Pesticide Screen', 'Sediment Analysis', 'Bacterial Count'];
const LOCATIONS = ['Sava — Ljubljana', 'Sava — Kranj', 'Drava — Maribor', 'Soča — Nova Gorica', 'Krka — Novo Mesto', 'Mura — Murska Sobota', 'Kolpa — Metlika', 'Savinja — Celje', 'Ljubljanica — Vrhnika', 'Kamniška Bistrica — Kamnik'];
const WORKERS = ['Marko Novak', 'Nina Kovač', 'Tomaž Horvat', 'Ana Kovač', 'Luka Zupan'];

function randomMeasurementAction(): { title: string; description: string; prompt: string } {
  const type = MEASUREMENT_TYPES[Math.floor(Math.random() * MEASUREMENT_TYPES.length)];
  const loc = LOCATIONS[Math.floor(Math.random() * LOCATIONS.length)];
  const worker = WORKERS[Math.floor(Math.random() * WORKERS.length)];
  const month = Math.floor(Math.random() * 6) + 3; // March–August
  const day = Math.floor(Math.random() * 25) + 1;
  const date = new Date(2026, month, day);
  const dateStr = date.toLocaleDateString('en-US', { month: 'long', day: 'numeric', year: 'numeric' });
  return {
    title: `Schedule ${type}`,
    description: `${loc} — ${worker}, ${dateStr}`,
    prompt: `Create a ${type} measurement at ${loc} and assign it to ${worker} for ${dateStr}`,
  };
}

/* ---- Quick Actions per role ---- */

const plannerQuickActions = [
  {
    title: 'Create a new plan',
    description: 'Start a monitoring plan from scratch or a template',
    prompt: 'Create a new river monitoring plan for the Sava basin in 2026',
  },
  {
    title: 'Generate a report',
    description: 'Summarize monitoring data into a report',
    prompt: 'Generate a quarterly report for River Monitoring 2026',
  },
  {
    title: 'Show anomalies',
    description: 'Review flagged measurements and alerts',
    prompt: 'Show me all anomalies detected in the last 30 days',
  },
  {
    title: 'Optimize budget',
    description: 'Find savings without sacrificing coverage',
    prompt: 'Analyze budget usage and suggest optimizations for Q2',
  },
];

const fieldWorkerQuickActions = [
  {
    title: 'My upcoming visits',
    description: 'View your next assigned monitoring visits',
    prompt: 'Show me my upcoming assigned visits with dates and locations',
  },
  {
    title: 'Measurement protocol',
    description: 'Check parameters and procedures for your next task',
    prompt: 'What measurement parameters do I need to collect for my next visit?',
  },
  {
    title: 'Report an observation',
    description: 'Document a field finding or anomaly',
    prompt: 'Help me document a field observation at my current monitoring location',
  },
  {
    title: 'Sample status',
    description: 'Track where your samples are in the pipeline',
    prompt: 'Show the pipeline status of all my recent samples',
  },
];

const labWorkerQuickActions = [
  {
    title: 'My lab queue',
    description: 'View samples waiting for your analysis',
    prompt: 'Show me the samples currently in my lab queue with their status and priority',
  },
  {
    title: 'Analysis parameters',
    description: 'Check parameter ranges and protocols',
    prompt: 'What are the acceptable parameter ranges for Basic Chemistry analysis?',
  },
  {
    title: 'Flag an anomaly',
    description: 'Report an unusual result from analysis',
    prompt: 'Help me document an anomalous result I found during laboratory analysis',
  },
  {
    title: 'Today\'s workload',
    description: 'See what needs to be analyzed today',
    prompt: 'Which samples do I need to analyze today and what are their priorities?',
  },
];

/* ---- Helpers ---- */

function getGreetingTime(): string {
  const hour = new Date().getHours();
  if (hour < 12) return 'Good morning';
  if (hour < 18) return 'Good afternoon';
  return 'Good evening';
}

function getFirstName(fullName: string): string {
  return fullName.split(' ')[0];
}


function formatDate(dateStr: string): string {
  return new Date(dateStr).toLocaleDateString('en-US', {
    month: 'short',
    day: 'numeric',
  });
}

/* ---- CSS ---- */

const css = `
.home{padding:2rem 1.5rem;width:100%;font-family:var(--font-sans)}
.greeting{text-align:center;margin-bottom:2rem}
.greeting h1{font-size:22px;font-weight:500;color:var(--color-text-primary);margin-bottom:4px}
.greeting p{font-size:14px;color:var(--color-text-secondary)}
.role-badge{display:inline-block;font-size:11px;padding:3px 10px;border-radius:var(--border-radius-md);margin-bottom:12px}
.role-planner{background:var(--color-background-info);color:var(--color-text-info)}
.role-field_worker{background:#FFF7ED;color:#BA7517}
.role-lab_worker{background:#F5F3FF;color:#8b5cf6}
.role-admin{background:#F3E8FF;color:#a855f7}
.role-analyst{background:#F0FDFA;color:#14b8a6}
.chat-input-area{position:relative;margin-bottom:2rem}
.chat-input{width:100%;padding:14px 48px 14px 16px;font-size:15px;border:0.5px solid var(--color-border-secondary);border-radius:var(--border-radius-lg);background:var(--color-background-primary);color:var(--color-text-primary);font-family:var(--font-sans);outline:none;transition:border-color .2s;box-sizing:border-box}
.chat-input:focus{border-color:var(--color-border-info)}
.chat-input::placeholder{color:var(--color-text-tertiary)}
.send-btn{position:absolute;right:10px;top:50%;transform:translateY(-50%);width:32px;height:32px;border-radius:50%;background:var(--color-text-info);border:none;cursor:pointer;display:flex;align-items:center;justify-content:center}
.send-btn:disabled{opacity:0.4;cursor:not-allowed}
.send-btn svg{width:16px;height:16px;fill:white}
.chat-messages{margin-bottom:1rem;position:relative}
.chat-clear-btn{position:sticky;top:0;float:right;z-index:5;width:24px;height:24px;border:0.5px solid var(--color-border-tertiary);border-radius:50%;background:var(--color-background-primary);color:var(--color-text-secondary);font-size:14px;cursor:pointer;display:flex;align-items:center;justify-content:center;box-shadow:0 1px 4px rgba(0,0,0,0.08)}
.chat-clear-btn:hover{background:var(--color-background-danger);color:var(--color-text-danger);border-color:var(--color-border-danger)}
.chat-msg{margin-bottom:12px;display:flex;gap:10px}
.chat-msg-user{justify-content:flex-end}
.chat-msg-user .chat-bubble{background:var(--color-text-info);color:white;border-radius:12px 12px 4px 12px;padding:10px 14px;max-width:80%;font-size:13px;line-height:1.5}
.chat-msg-assistant .chat-bubble{background:var(--color-background-secondary);color:var(--color-text-primary);border-radius:12px 12px 12px 4px;padding:10px 14px;max-width:80%;font-size:13px;line-height:1.5}
.chat-msg-assistant .chat-bubble h1{font-size:16px;font-weight:600;margin:12px 0 6px;color:var(--color-text-primary)}
.chat-msg-assistant .chat-bubble h1:first-child{margin-top:0}
.chat-msg-assistant .chat-bubble h2{font-size:14px;font-weight:600;margin:10px 0 4px;color:var(--color-text-primary)}
.chat-msg-assistant .chat-bubble h3{font-size:13px;font-weight:600;margin:8px 0 4px;color:var(--color-text-primary)}
.chat-msg-assistant .chat-bubble p{margin:4px 0}
.chat-msg-assistant .chat-bubble ul,.chat-msg-assistant .chat-bubble ol{margin:4px 0;padding-left:18px}
.chat-msg-assistant .chat-bubble li{margin:2px 0}
.chat-msg-assistant .chat-bubble strong{font-weight:600;color:var(--color-text-primary)}
.chat-msg-assistant .chat-bubble hr{border:none;border-top:0.5px solid var(--color-border-tertiary);margin:8px 0}
.chat-msg-assistant .chat-bubble code{background:var(--color-background-tertiary,rgba(0,0,0,0.06));padding:1px 4px;border-radius:3px;font-size:12px}
.chat-msg-assistant .chat-bubble table{width:100%;border-collapse:collapse;margin:6px 0;font-size:12px}
.chat-msg-assistant .chat-bubble th{text-align:left;font-weight:500;padding:3px 8px 3px 0;border-bottom:0.5px solid var(--color-border-tertiary);color:var(--color-text-secondary)}
.chat-msg-assistant .chat-bubble td{padding:3px 8px 3px 0;color:var(--color-text-primary)}
.chat-card{background:var(--color-background-secondary);border:0.5px solid var(--color-border-tertiary);border-radius:var(--border-radius-md);padding:10px 14px;margin-top:8px;font-size:12px}
.chat-card-title{font-weight:500;color:var(--color-text-primary);margin-bottom:6px;font-size:13px}
.chat-card-grid{display:grid;grid-template-columns:1fr 1fr;gap:6px}
.chat-card-item-label{color:var(--color-text-secondary);font-size:11px}
.chat-card-item-value{color:var(--color-text-primary);font-size:12px;font-weight:500}
.chat-card-list{list-style:none;padding:0;margin:0}
.chat-card-list li{padding:3px 0;color:var(--color-text-primary);font-size:12px}
.chat-card-list li::before{content:"\\2022 ";color:var(--color-text-secondary);margin-right:6px}
.chat-card-table{width:100%;border-collapse:collapse;font-size:11px}
.chat-card-table th{text-align:left;color:var(--color-text-secondary);font-weight:500;padding:3px 8px 3px 0;border-bottom:0.5px solid var(--color-border-tertiary)}
.chat-card-table td{color:var(--color-text-primary);padding:3px 8px 3px 0}
.chat-card-suggestions li{display:flex;align-items:flex-start;gap:6px;padding:3px 0}
.chat-card-suggestions li::before{content:"\\2713";color:#639922;font-weight:bold;flex-shrink:0}
.chat-card-footer{display:flex;gap:12px;margin-top:8px;padding-top:6px;border-top:0.5px solid var(--color-border-tertiary);font-size:11px;color:var(--color-text-secondary)}
.chat-card-footer span strong{color:var(--color-text-primary)}
.typing-indicator{display:flex;align-items:center;gap:8px;color:var(--color-text-secondary);font-size:13px;margin-bottom:12px}
.typing-dots{display:flex;gap:3px}
.typing-dots span{width:6px;height:6px;border-radius:50%;background:var(--color-text-tertiary);animation:typingBounce 1.2s ease-in-out infinite}
.typing-dots span:nth-child(2){animation-delay:0.2s}
.typing-dots span:nth-child(3){animation-delay:0.4s}
@keyframes typingBounce{0%,60%,100%{transform:translateY(0)}30%{transform:translateY(-4px)}}
.quick-actions{display:grid;grid-template-columns:1fr 1fr;gap:10px;margin-bottom:2rem}
.qa-card{padding:12px 14px;border:0.5px solid var(--color-border-tertiary);border-radius:var(--border-radius-lg);cursor:pointer;transition:border-color .2s,background .15s;background:none}
.qa-card:hover{border-color:var(--color-border-secondary);background:var(--color-background-secondary)}
.qa-label{font-size:13px;font-weight:500;color:var(--color-text-primary);margin-bottom:2px;text-align:left}
.qa-desc{font-size:12px;color:var(--color-text-secondary);text-align:left}
.section-label{font-size:12px;font-weight:500;color:var(--color-text-tertiary);text-transform:uppercase;letter-spacing:0.5px;margin-bottom:10px}
.stats-row{display:grid;grid-template-columns:repeat(4,1fr);gap:10px;margin-bottom:2rem}
.stats-row-3{grid-template-columns:repeat(3,1fr)}
.stat-card{background:var(--color-background-secondary);border-radius:var(--border-radius-md);padding:12px 14px}
.stat-label{font-size:11px;color:var(--color-text-secondary);margin-bottom:4px}
.stat-val{font-size:20px;font-weight:500;color:var(--color-text-primary)}
.stat-sub{font-size:11px;color:var(--color-text-secondary);margin-top:2px}
.stat-good{color:#639922}.stat-warn{color:#BA7517}.stat-bad{color:#E24B4A}
.tasks-list{display:flex;flex-direction:column;gap:8px}
.task-item{display:flex;align-items:center;gap:12px;padding:10px 14px;border:0.5px solid var(--color-border-tertiary);border-radius:var(--border-radius-md);transition:background .15s}
.task-item:hover{background:var(--color-background-secondary)}
.task-dot{width:8px;height:8px;border-radius:50%;flex-shrink:0}
.dot-planned{background:#378ADD}.dot-overdue{background:#E24B4A}.dot-today{background:#639922}
.task-info{flex:1;min-width:0}
.task-title{font-size:13px;font-weight:500;color:var(--color-text-primary);white-space:nowrap;overflow:hidden;text-overflow:ellipsis}
.task-meta{font-size:11px;color:var(--color-text-secondary)}
.task-badge{font-size:10px;padding:2px 8px;border-radius:var(--border-radius-md);flex-shrink:0}
.badge-today{background:var(--color-background-success);color:var(--color-text-success)}
.badge-overdue{background:var(--color-background-danger);color:var(--color-text-danger)}
.badge-upcoming{background:var(--color-background-info);color:var(--color-text-info)}

.chat-actions{display:flex;flex-wrap:wrap;gap:6px;margin-top:8px;max-width:80%}
.chat-action-btn{display:inline-flex;align-items:center;gap:5px;padding:6px 12px;font-size:12px;font-weight:500;font-family:var(--font-sans);border:0.5px solid var(--color-border-info,#378ADD);border-radius:var(--border-radius-md);background:var(--color-background-primary);color:var(--color-text-info,#378ADD);cursor:pointer;transition:all .15s;white-space:nowrap}
.chat-action-btn:hover{background:var(--color-background-info);color:var(--color-text-info)}
.chat-action-btn:disabled{opacity:0.5;cursor:not-allowed}
.chat-action-btn svg{width:13px;height:13px;flex-shrink:0}
.chat-action-dropdown{position:relative;display:inline-flex}
.chat-action-dropdown .chat-action-btn{border-radius:var(--border-radius-md);padding-right:8px}
.chat-action-chevron{margin-left:2px;width:10px;height:10px;transition:transform .15s}
.chat-action-chevron.open{transform:rotate(180deg)}
.chat-dropdown-menu{position:absolute;top:calc(100% + 4px);left:0;min-width:200px;background:var(--color-background-primary);border:0.5px solid var(--color-border-secondary);border-radius:var(--border-radius-md);box-shadow:0 4px 12px rgba(0,0,0,0.1);z-index:10;overflow:hidden}
.chat-dropdown-item{display:block;width:100%;padding:8px 12px;font-size:12px;font-family:var(--font-sans);color:var(--color-text-primary);background:none;border:none;text-align:left;cursor:pointer;transition:background .12s}
.chat-dropdown-item:hover{background:var(--color-background-info)}
.chat-dropdown-item:not(:last-child){border-bottom:0.5px solid var(--color-border-tertiary)}

@media(max-width:600px){
  .stats-row{grid-template-columns:repeat(2,1fr)}
  .quick-actions{grid-template-columns:1fr}
  .chat-actions{max-width:100%}
}

/* Measurement preview card */
.meas-preview{max-width:80%;margin:8px 0 12px;border:1.5px solid var(--color-border-info);border-radius:var(--border-radius-lg);background:var(--color-background-primary);overflow:hidden;box-shadow:0 2px 8px rgba(55,138,221,0.08)}
.meas-preview.meas-created{border-color:#639922;opacity:0.85}
.meas-preview-header{display:flex;align-items:center;gap:8px;padding:12px 16px;background:var(--color-background-info);border-bottom:0.5px solid var(--color-border-tertiary)}
.meas-preview-title{font-size:13px;font-weight:600;color:var(--color-text-info)}
.meas-created-badge{margin-left:auto;font-size:10px;font-weight:600;color:#639922;background:#EFF6E8;padding:2px 8px;border-radius:var(--border-radius-md)}
.meas-preview-grid{display:grid;grid-template-columns:1fr 1fr;gap:8px;padding:14px 16px}
.meas-preview-field{display:flex;flex-direction:column;gap:1px}
.meas-preview-label{font-size:9px;font-weight:600;color:var(--color-text-tertiary);text-transform:uppercase;letter-spacing:0.3px}
.meas-preview-value{font-size:13px;font-weight:500;color:var(--color-text-primary)}
.meas-preview-rationale{padding:0 16px 10px;font-size:11px;color:var(--color-text-secondary);font-style:italic}
.meas-preview-btn{display:block;width:calc(100% - 32px);margin:0 16px 14px;padding:10px;border:none;border-radius:var(--border-radius-md);background:#378ADD;color:white;font-size:13px;font-weight:600;font-family:var(--font-sans);cursor:pointer;transition:background .15s}
.meas-preview-btn:hover{background:#2d78c4}
.meas-preview-done{padding:0 16px 14px;font-size:12px;color:#639922;font-weight:500;display:flex;align-items:center;gap:6px}
.meas-preview-done::before{content:"\\2713";font-weight:bold}
.meas-approve-row{display:flex;align-items:center;gap:8px;padding:10px 16px 14px;flex-wrap:wrap}
.meas-approve-label{font-size:12px;font-weight:500;color:var(--color-text-primary);flex:1;min-width:150px}
.meas-approve-yes{padding:7px 16px;border:none;border-radius:var(--border-radius-md);background:#639922;color:white;font-size:12px;font-weight:600;font-family:var(--font-sans);cursor:pointer}
.meas-approve-yes:hover{background:#4d7a1a}
.meas-approve-no{padding:7px 12px;border:0.5px solid var(--color-border-tertiary);border-radius:var(--border-radius-md);background:none;color:var(--color-text-secondary);font-size:12px;font-family:var(--font-sans);cursor:pointer}
.meas-approve-no:hover{background:var(--color-background-secondary)}
.meas-preview-cost{margin-left:auto;font-size:12px;font-weight:600;color:var(--color-text-primary)}
.meas-preview-item{border-top:0.5px solid var(--color-border-tertiary)}
.meas-preview-item:first-of-type{border-top:none}

/* AI structured cards — shared */
.ai-card{max-width:80%;margin:8px 0 12px;border-radius:var(--border-radius-lg);background:var(--color-background-primary);overflow:hidden;box-shadow:0 2px 8px rgba(0,0,0,0.06)}
.ai-card-header{display:flex;align-items:center;gap:8px;padding:10px 16px;font-size:13px;font-weight:600;border-bottom:0.5px solid var(--color-border-tertiary)}
.ai-card-icon{width:22px;height:22px;border-radius:50%;display:flex;align-items:center;justify-content:center;font-size:11px;font-weight:700;color:#fff;flex-shrink:0}

/* Budget card */
.ai-card-budget{border:1.5px solid #639922}
.ai-card-budget .ai-card-header{background:#EFF6E8;color:#639922}
.ai-card-budget .ai-card-icon{background:#639922}
.ai-suggestion{padding:10px 16px;border-bottom:0.5px solid var(--color-border-tertiary)}
.ai-suggestion:last-of-type{border-bottom:none}
.ai-suggestion-top{display:flex;align-items:center;gap:6px;margin-bottom:4px;flex-wrap:wrap}
.ai-suggestion-type{font-size:9px;font-weight:600;padding:2px 6px;border-radius:3px;text-transform:uppercase;background:var(--color-background-secondary);color:var(--color-text-secondary)}
.ai-sug-grouping{background:#EBF3FB;color:#378ADD}
.ai-sug-frequency_reduction{background:#FEF3C7;color:#D97706}
.ai-sug-rebalancing{background:#F0FDF4;color:#639922}
.ai-sug-contractor{background:#F5F3FF;color:#8B5CF6}
.ai-suggestion-savings{font-size:12px;font-weight:600;color:#639922}
.ai-suggestion-risk{font-size:9px;padding:1px 5px;border-radius:3px;font-weight:500}
.risk-low{background:#EFF6E8;color:#639922}
.risk-medium{background:#FEF3C7;color:#D97706}
.risk-high{background:#FEF2F2;color:#E24B4A}
.ai-suggestion-title{font-size:12px;font-weight:600;color:var(--color-text-primary);margin-bottom:2px}
.ai-suggestion-desc{font-size:11px;color:var(--color-text-secondary);line-height:1.4}
.ai-card-total{padding:10px 16px;font-size:13px;font-weight:600;color:#639922;border-top:1.5px solid #639922;background:#EFF6E8}

/* Anomaly card */
.ai-card-anomaly{border:1.5px solid #E24B4A}
.ai-card-anomaly .ai-card-header{background:#FCEBEB;color:#E24B4A}
.ai-card-anomaly .ai-card-icon{background:#E24B4A}
.ai-anomaly{padding:10px 16px;border-bottom:0.5px solid var(--color-border-tertiary)}
.ai-anomaly-warning{border-left:3px solid #EF9F27}
.ai-anomaly-critical{border-left:3px solid #E24B4A}
.ai-anomaly-top{display:flex;align-items:center;justify-content:space-between;margin-bottom:4px}
.ai-anomaly-loc{font-size:12px;font-weight:600;color:var(--color-text-primary)}
.ai-anomaly-sev{font-size:9px;font-weight:600;padding:2px 6px;border-radius:3px;text-transform:uppercase}
.sev-warning{background:#FEF3C7;color:#D97706}
.sev-critical{background:#FEF2F2;color:#E24B4A}
.ai-anomaly-param{font-size:11px;color:var(--color-text-secondary);margin-bottom:3px}
.ai-anomaly-param strong{color:var(--color-text-primary);font-size:13px}
.ai-anomaly-rec{font-size:11px;color:var(--color-text-info);font-style:italic}

/* Report card */
.ai-card-report{border:1.5px solid #378ADD}
.ai-card-report .ai-card-header{background:#EBF3FB;color:#378ADD}
.ai-card-report .ai-card-icon{background:#378ADD}
.ai-report-period{padding:4px 16px;font-size:11px;color:var(--color-text-secondary)}
.ai-report-metrics{display:flex;gap:8px;padding:8px 16px;flex-wrap:wrap}
.ai-report-metric{display:flex;flex-direction:column;padding:6px 10px;background:var(--color-background-secondary);border-radius:var(--border-radius-md);min-width:70px}
.ai-report-metric-label{font-size:8px;color:var(--color-text-tertiary);text-transform:uppercase;letter-spacing:0.3px}
.ai-report-metric-val{font-size:14px;font-weight:600;color:var(--color-text-primary)}
.ai-report-section{padding:8px 16px}
.ai-report-heading{font-size:12px;font-weight:600;color:var(--color-text-primary);margin-bottom:3px}
.ai-report-content{font-size:11px;color:var(--color-text-secondary);line-height:1.5}

/* Field notes card */
.ai-card-fieldnotes{border:1.5px solid #BA7517}
.ai-card-fieldnotes .ai-card-header{background:#FEF3C7;color:#BA7517}
.ai-card-fieldnotes .ai-card-icon{background:#BA7517}
.ai-fn-grid{padding:10px 16px;display:grid;grid-template-columns:1fr 1fr;gap:8px}
.ai-fn-field{display:flex;flex-direction:column;gap:1px;font-size:12px;color:var(--color-text-primary)}
.ai-fn-label{font-size:9px;font-weight:600;color:var(--color-text-tertiary);text-transform:uppercase;letter-spacing:0.3px}
.ai-fn-flags{padding:6px 16px 10px;display:flex;gap:4px;flex-wrap:wrap}
.ai-fn-flag{font-size:10px;font-weight:500;padding:2px 8px;border-radius:var(--border-radius-md);background:#FEF2F2;color:#E24B4A;border:0.5px solid #fecaca}

/* Reliability badge */
.ai-reliability{font-size:9px;font-weight:600;padding:2px 6px;border-radius:3px;border:1px solid;margin-left:auto;white-space:nowrap;flex-shrink:0}

/* PDF export button */
.ai-report-pdf{display:flex;align-items:center;gap:4px;margin-left:auto;padding:4px 10px;border:0.5px solid var(--color-border-tertiary);border-radius:var(--border-radius-md);background:var(--color-background-primary);color:var(--color-text-info);font-size:10px;font-weight:600;font-family:var(--font-sans);cursor:pointer;flex-shrink:0;transition:all .12s}
.ai-report-pdf:hover{background:var(--color-background-info);border-color:var(--color-border-info)}
`;

/* ---- Component ---- */

export default function HomeScreen() {
  const { dashboardStats, visits, measurements, users, locations, measurementTemplates, monitoringPlans, planBuilderEntries, activityItems, addVisits, addMeasurements, addPlanBuilderEntries } = useDatabase();
  const { currentUser } = useUser();

  function getUpcomingTasks(userId?: string) {
    const now = new Date();
    return visits
      .filter((v) => {
        const matchStatus = v.status === 'planned' || v.status === 'in_progress';
        if (userId) return matchStatus && v.assigned_to === userId;
        return matchStatus;
      })
      .sort((a, b) => a.planned_date.localeCompare(b.planned_date))
      .slice(0, 4)
      .map((v) => {
        const location = locations.find((l) => l.id === v.location_id);
        const visitMeasurements = measurements.filter((m) => m.visit_id === v.id);
        const template = visitMeasurements.length
          ? measurementTemplates.find((t) => t.id === visitMeasurements[0].measurement_template_id)
          : null;
        const assignee = users.find((u) => u.id === v.assigned_to);
        const visitDate = new Date(v.planned_date);
        const diffDays = Math.ceil((visitDate.getTime() - now.getTime()) / (1000 * 60 * 60 * 24));

        let dotClass = 'dot-planned';
        let badgeClass = 'badge-upcoming';
        let badgeLabel = `In ${diffDays}d`;

        if (diffDays < 0) {
          dotClass = 'dot-overdue';
          badgeClass = 'badge-overdue';
          badgeLabel = 'Overdue';
        } else if (diffDays === 0) {
          dotClass = 'dot-today';
          badgeClass = 'badge-today';
          badgeLabel = 'Today';
        } else if (diffDays === 1) {
          dotClass = 'dot-today';
          badgeClass = 'badge-today';
          badgeLabel = 'Tomorrow';
        }

        return {
          id: v.id,
          name: location?.name ?? 'Unknown',
          measurementType: template?.name ?? 'General',
          assignee: assignee?.full_name ?? 'Unassigned',
          date: v.planned_date,
          dotClass,
          badgeClass,
          badgeLabel,
        };
      });
  }
  const { messages, setMessages, chatInput, setChatInput, clearChat } = useChat();
  const [isTyping, setIsTyping] = useState(false);
  const [openDropdown, setOpenDropdown] = useState<string | null>(null);
  const [createdPreviews, setCreatedPreviews] = useState<Set<string>>(new Set());
  const [pendingApproval, setPendingApproval] = useState<Set<string>>(new Set());
  const lastAssistantRef = useRef<HTMLDivElement>(null);
  const inputRef = useRef<HTMLInputElement>(null);

  // User ID → Worker ID mapping (PlanBuilder uses worker IDs)
  const userToWorker: Record<string, string> = { u2: 'w1', u4: 'w2' };
  let _aiEntryCounter = useRef(0);

  const handleCreateAllMeasurements = (msgId: string, previews: MeasurementPreview[]) => {
    const planId = monitoringPlans[0]?.id ?? 'p1';
    const newEntries: Entry[] = [];
    const newVisits: Visit[] = [];
    const newMeasurements: Measurement[] = [];

    for (const preview of previews) {
      const uid = `ai-${Date.now()}-${++_aiEntryCounter.current}`;
      const loc = locations.find(l => l.id === preview.locationId);
      const workerId = userToWorker[preview.assigneeId] || preview.assigneeId || '';

      newEntries.push({
        id: uid,
        locationId: preview.locationId,
        locationName: preview.locationName,
        locationCode: loc?.code ?? '',
        rating: (loc?.rating ?? 'moderate') as Entry['rating'],
        river: preview.locationName.split(' — ')[0] ?? preview.locationName,
        program: 'river' as const,
        waterBody: 'river' as const,
        measurement: preview.measurementName,
        frequency: (preview.frequency || 'quarterly') as Entry['frequency'],
        assigneeId: workerId,
        status: 'planned' as const,
        nextDate: preview.plannedDate,
        cost: preview.estimatedCost,
      });

      newVisits.push({
        id: `${uid}-v`,
        plan_id: planId,
        location_id: preview.locationId,
        planned_date: preview.plannedDate,
        status: 'planned',
        assigned_to: preview.assigneeId,
        logistics_cost: 50,
      });

      newMeasurements.push({
        id: `${uid}-m`,
        location_id: preview.locationId,
        measurement_template_id: preview.measurementTemplateId,
        plan_entry_id: uid,
        visit_id: `${uid}-v`,
        assignee_id: preview.assigneeId,
        status: 'planned',
        pipeline_status: 'pending_sample',
        planned_date: preview.plannedDate,
        analysis_cost: preview.estimatedCost,
      });
    }

    addPlanBuilderEntries(newEntries);
    addVisits(newVisits);
    addMeasurements(newMeasurements);
    setCreatedPreviews(prev => new Set(prev).add(msgId));
  };

  const isFieldWorker = currentUser.role === 'field_worker';
  const isLabWorker = currentUser.role === 'lab_worker';
  const dynamicAction = useMemo(() => randomMeasurementAction(), []);
  const quickActions = isLabWorker
    ? labWorkerQuickActions
    : isFieldWorker ? fieldWorkerQuickActions : [...plannerQuickActions, dynamicAction];

  // For field workers, show only their tasks; for planners show all
  const upcomingTasks = isFieldWorker
    ? getUpcomingTasks(currentUser.id)
    : getUpcomingTasks();

  const budgetPercent = Math.round(
    (dashboardStats.budgetUsed / dashboardStats.totalBudget) * 100
  );

  // Field worker stats
  const myVisitsTotal = visits.filter(v => v.assigned_to === currentUser.id).length;
  const myVisitsPending = visits.filter(v => v.assigned_to === currentUser.id && (v.status === 'planned' || v.status === 'in_progress')).length;
  const myMeasurementsCount = measurements.filter(m => m.assignee_id === currentUser.id).length;

  // Lab worker stats
  const labSamples = measurements.filter(m => m.lab_assignee_id === currentUser.id);
  const labInTransit = labSamples.filter(m => m.pipeline_status === 'in_transit').length;
  const labInLab = labSamples.filter(m => m.pipeline_status === 'in_lab').length;
  const labAnalyzed = labSamples.filter(m => m.pipeline_status === 'analyzed').length;
  const labTotal = labSamples.length;

  // Build live database context for AI
  const dbContext = useMemo(() => {
    const lines: string[] = [];

    // Dashboard stats
    lines.push(`DASHBOARD: ${dashboardStats.activePlans} active plans, ${dashboardStats.visitsThisMonth} visits this month (${dashboardStats.pendingVisits} pending), budget ${Math.round((dashboardStats.budgetUsed / dashboardStats.totalBudget) * 100)}% used (€${dashboardStats.budgetUsed.toLocaleString()} of €${dashboardStats.totalBudget.toLocaleString()}), ${dashboardStats.anomalyCount} anomalies`);

    // Monitoring plans
    lines.push(`\nMONITORING PLANS (${monitoringPlans.length}):`);
    for (const p of monitoringPlans) {
      lines.push(`- ${p.name} (${p.id}): status=${p.status}, budget=€${p.total_budget?.toLocaleString() ?? '?'}, program=${p.program_type}, year=${p.year}`);
    }

    // Locations summary (top 20 + counts)
    const locsByRating: Record<string, number> = {};
    for (const l of locations) locsByRating[l.rating] = (locsByRating[l.rating] || 0) + 1;
    lines.push(`\nLOCATIONS (${locations.length} total): ${Object.entries(locsByRating).map(([r, c]) => `${r}=${c}`).join(', ')}`);
    for (const l of locations.slice(0, 20)) {
      lines.push(`- ${l.name} (${l.code}): rating=${l.rating}, type=${l.environment_type}, coords=${l.latitude.toFixed(4)},${l.longitude.toFixed(4)}`);
    }
    if (locations.length > 20) lines.push(`  ... and ${locations.length - 20} more locations`);

    // Measurement templates
    lines.push(`\nMEASUREMENT TEMPLATES (${measurementTemplates.length}):`);
    for (const t of measurementTemplates) {
      lines.push(`- ${t.name} (${t.id}): cost=€${t.unit_cost}, params=${t.parameters.map(p => `${p.label}(${p.unit})`).join(', ')}`);
    }

    // Visits summary
    const visitsByStatus: Record<string, number> = {};
    for (const v of visits) visitsByStatus[v.status] = (visitsByStatus[v.status] || 0) + 1;
    lines.push(`\nVISITS (${visits.length} total): ${Object.entries(visitsByStatus).map(([s, c]) => `${s}=${c}`).join(', ')}`);
    const upcomingVisits = visits.filter(v => v.status === 'planned' || v.status === 'in_progress').slice(0, 15);
    for (const v of upcomingVisits) {
      const loc = locations.find(l => l.id === v.location_id);
      const assignee = users.find(u => u.id === v.assigned_to);
      lines.push(`- Visit ${v.id}: ${loc?.name ?? v.location_id}, date=${v.planned_date}, status=${v.status}, assignee=${assignee?.full_name ?? v.assigned_to ?? 'unassigned'}`);
    }

    // Measurements pipeline
    const measByPipeline: Record<string, number> = {};
    for (const m of measurements) measByPipeline[m.pipeline_status] = (measByPipeline[m.pipeline_status] || 0) + 1;
    lines.push(`\nMEASUREMENTS PIPELINE (${measurements.length} total): ${Object.entries(measByPipeline).map(([s, c]) => `${s}=${c}`).join(', ')}`);

    // Anomalies from activity items (Supabase)
    const anomalyItems = activityItems.filter(a => a.hasAnomaly);
    if (anomalyItems.length > 0) {
      lines.push(`\nACTIVE ANOMALIES (${anomalyItems.length}):`);
      for (const a of anomalyItems) {
        lines.push(`- ${a.location?.name || 'Unknown'}: ${a.measurementType}, pH=${a.lastPh ?? '—'}, trend=${a.phTrend || 'Stable'}`);
      }
    }

    // Station overview from locations (Supabase)
    const stByEnv: Record<string, number> = {};
    const stByRating: Record<string, number> = {};
    for (const loc of locations) {
      stByEnv[loc.environment_type] = (stByEnv[loc.environment_type] || 0) + 1;
      stByRating[loc.rating] = (stByRating[loc.rating] || 0) + 1;
    }
    lines.push(`\nMONITORING STATIONS (${locations.length}): by type: ${Object.entries(stByEnv).map(([p, c]) => `${p}=${c}`).join(', ')}; by rating: ${Object.entries(stByRating).map(([r, c]) => `${r}=${c}`).join(', ')}`);

    // Plan builder entries
    if (planBuilderEntries.length > 0) {
      const pbByStatus: Record<string, number> = {};
      for (const e of planBuilderEntries) pbByStatus[e.status] = (pbByStatus[e.status] || 0) + 1;
      lines.push(`\nPLAN BUILDER ENTRIES (${planBuilderEntries.length}): ${Object.entries(pbByStatus).map(([s, c]) => `${s}=${c}`).join(', ')}`);
      const totalCost = planBuilderEntries.reduce((sum, e) => sum + e.cost, 0);
      lines.push(`Total planned cost: €${totalCost.toLocaleString()}`);
    }

    // Users
    lines.push(`\nUSERS (${users.length}):`);
    for (const u of users) {
      lines.push(`- ${u.full_name} (${u.id}): role=${u.role}`);
    }

    return lines.join('\n');
  }, [dashboardStats, monitoringPlans, locations, measurementTemplates, visits, measurements, users, planBuilderEntries]);

  // Clear chat when user switches
  useEffect(() => {
    clearChat();
  }, [currentUser.id]);

  useEffect(() => {
    if (lastAssistantRef.current) {
      lastAssistantRef.current.scrollIntoView({ behavior: 'smooth', block: 'start' });
    }
  }, [messages]);

  useEffect(() => {
    if (!openDropdown) return;
    const close = () => setOpenDropdown(null);
    document.addEventListener('click', close);
    return () => document.removeEventListener('click', close);
  }, [openDropdown]);

  const handleSend = () => {
    const text = chatInput.trim();
    if (!text || isTyping) return;

    const userMsg: ChatMessage = {
      id: `msg-${Date.now()}`,
      role: 'user',
      content: text,
      timestamp: new Date().toISOString(),
    };
    setMessages((prev) => [...prev, userMsg]);
    setChatInput('');
    setIsTyping(true);

    const history = messages.map(m => ({ role: m.role, content: m.content }));
    queryAI(text, history, currentUser, dbContext).then(response => {
      const assistantMsg: ChatMessage = {
        id: `msg-${Date.now()}-resp`,
        role: 'assistant',
        content: response.text,
        timestamp: new Date().toISOString(),
        actions: response.actions,
        measurementPreview: response.measurementPreview,
        measurementPreviews: response.measurementPreviews,
        budgetSuggestions: response.budgetSuggestions as unknown[],
        anomalies: response.anomalies as unknown[],
        report: response.report as unknown,
        fieldNotes: response.fieldNotes as unknown,
      };
      setMessages((prev) => [...prev, assistantMsg]);
      setIsTyping(false);
    });
  };

  const handleKeyDown = (e: React.KeyboardEvent) => {
    if (e.key === 'Enter') {
      e.preventDefault();
      handleSend();
    }
  };

  const handleQuickAction = (prompt: string) => {
    setChatInput(prompt);
    inputRef.current?.focus();
  };

  const sendActionPrompt = (prompt: string) => {
    if (isTyping) return;
    setOpenDropdown(null);
    const userMsg: ChatMessage = {
      id: `msg-${Date.now()}`,
      role: 'user',
      content: prompt,
      timestamp: new Date().toISOString(),
    };
    setMessages((prev) => [...prev, userMsg]);
    setIsTyping(true);
    const history = messages.map(m => ({ role: m.role, content: m.content }));
    queryAI(prompt, [...history, { role: 'user', content: prompt }], currentUser, dbContext).then(response => {
      const assistantMsg: ChatMessage = {
        id: `msg-${Date.now()}-resp`,
        role: 'assistant',
        content: response.text,
        timestamp: new Date().toISOString(),
        actions: response.actions,
        measurementPreview: response.measurementPreview,
        measurementPreviews: response.measurementPreviews,
        budgetSuggestions: response.budgetSuggestions as unknown[],
        anomalies: response.anomalies as unknown[],
        report: response.report as unknown,
        fieldNotes: response.fieldNotes as unknown,
      };
      setMessages((prev) => [...prev, assistantMsg]);
      setIsTyping(false);
    });
  };

  const handleActionClick = (action: ChatAction) => {
    if (action.type === 'prompt' && action.prompt) {
      sendActionPrompt(action.prompt);
    } else if (action.type === 'dropdown') {
      setOpenDropdown(openDropdown === action.id ? null : action.id);
    }
  };

  const roleLabel = getRoleLabel(currentUser.role);
  const placeholderText = isLabWorker
    ? 'Ask about samples, analysis parameters, or results...'
    : isFieldWorker
    ? 'Ask about your assigned tasks, protocols, or samples...'
    : 'Ask the AI assistant anything...';

  return (
    <>
      <style>{css}</style>
      <div className="home">
        {/* Greeting */}
        <div className="greeting">
          <span className={`role-badge role-${currentUser.role}`}>
            {roleLabel}
          </span>
          <h1>{getGreetingTime()}, {getFirstName(currentUser.full_name)}</h1>
          <p>{isLabWorker ? 'Here is your lab queue and analysis work.' : isFieldWorker ? 'Here are your assigned tasks and field work.' : 'What would you like to do today?'}</p>
        </div>

        {/* Chat input area */}
        <div className="chat-input-area">
          <input
            ref={inputRef}
            type="text"
            className="chat-input"
            placeholder={placeholderText}
            value={chatInput}
            onChange={(e) => setChatInput(e.target.value)}
            onKeyDown={handleKeyDown}
          />
          <button
            className="send-btn"
            onClick={handleSend}
            disabled={!chatInput.trim() || isTyping}
          >
            <svg viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg">
              <path d="M2.01 21L23 12 2.01 3 2 10l15 2-15 2z" />
            </svg>
          </button>
        </div>

        {/* Chat messages inline */}
        {(messages.length > 0 || isTyping) && (
          <div className="chat-messages">
            <button className="chat-clear-btn" onClick={clearChat} title="Clear conversation">&times;</button>
            {messages.map((msg, msgIndex) => {
              const isLastAssistant = msg.role === 'assistant' &&
                messages.slice(msgIndex + 1).every(m => m.role !== 'assistant');
              return (
              <div key={msg.id} ref={isLastAssistant ? lastAssistantRef : undefined}>
                <div className={`chat-msg chat-msg-${msg.role}`}>
                  <div className="chat-bubble">
                    {msg.role === 'assistant' ? (
                      <ReactMarkdown>{msg.content}</ReactMarkdown>
                    ) : (
                      msg.content
                    )}
                  </div>
                </div>
                {msg.cards?.map((card, idx) => (
                  <ChatCardRenderer key={idx} card={card} />
                ))}
                {/* Measurement previews (batch) */}
                {msg.measurementPreviews && msg.measurementPreviews.length > 0 && (
                  <div className={`meas-preview${createdPreviews.has(msg.id) ? ' meas-created' : ''}`}>
                    <div className="meas-preview-header">
                      <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2"><path d="M12 5v14M5 12h14"/></svg>
                      <span className="meas-preview-title">{msg.measurementPreviews.length === 1 ? 'New Measurement' : `${msg.measurementPreviews.length} New Measurements`}</span>
                      <span className="meas-preview-cost">€{msg.measurementPreviews.reduce((s, p) => s + p.estimatedCost, 0).toLocaleString()}</span>
                      {createdPreviews.has(msg.id) && <span className="meas-created-badge">Created</span>}
                    </div>
                    {msg.measurementPreviews.map((p, pi) => (
                      <div key={pi} className="meas-preview-item">
                        <div className="meas-preview-grid">
                          <div className="meas-preview-field"><span className="meas-preview-label">Location</span><span className="meas-preview-value">{p.locationName}</span></div>
                          <div className="meas-preview-field"><span className="meas-preview-label">Measurement</span><span className="meas-preview-value">{p.measurementName}</span></div>
                          <div className="meas-preview-field"><span className="meas-preview-label">Assigned to</span><span className="meas-preview-value">{p.assigneeName}</span></div>
                          <div className="meas-preview-field"><span className="meas-preview-label">Date</span><span className="meas-preview-value">{p.plannedDate}</span></div>
                          <div className="meas-preview-field"><span className="meas-preview-label">Frequency</span><span className="meas-preview-value">{p.frequency}</span></div>
                          <div className="meas-preview-field"><span className="meas-preview-label">Est. cost</span><span className="meas-preview-value">€{p.estimatedCost}</span></div>
                        </div>
                        {p.rationale && <div className="meas-preview-rationale">{p.rationale}</div>}
                      </div>
                    ))}
                    {!createdPreviews.has(msg.id) ? (
                      pendingApproval.has(msg.id) ? (
                        <div className="meas-approve-row">
                          <span className="meas-approve-label">Are you sure you want to create {msg.measurementPreviews.length === 1 ? 'this measurement' : `${msg.measurementPreviews.length} measurements`}?</span>
                          <button className="meas-approve-yes" onClick={() => { handleCreateAllMeasurements(msg.id, msg.measurementPreviews!); setPendingApproval(prev => { const n = new Set(prev); n.delete(msg.id); return n; }); }}>
                            Confirm &amp; Create
                          </button>
                          <button className="meas-approve-no" onClick={() => setPendingApproval(prev => { const n = new Set(prev); n.delete(msg.id); return n; })}>
                            Cancel
                          </button>
                        </div>
                      ) : (
                        <button className="meas-preview-btn" onClick={() => setPendingApproval(prev => new Set(prev).add(msg.id))}>
                          {msg.measurementPreviews.length === 1 ? 'Create this measurement' : `Create all ${msg.measurementPreviews.length} measurements`}
                        </button>
                      )
                    ) : (
                      <div className="meas-preview-done">{msg.measurementPreviews.length} measurement{msg.measurementPreviews.length > 1 ? 's' : ''} created and synced to Plan Builder, Visits, and Planned Work.</div>
                    )}
                  </div>
                )}

                {/* Budget suggestions */}
                {(msg.budgetSuggestions as BudgetSuggestion[] | undefined)?.length ? (
                  <div className="ai-card ai-card-budget">
                    <div className="ai-card-header"><span className="ai-card-icon">€</span>Budget Optimization</div>
                    {(msg.budgetSuggestions as BudgetSuggestion[]).map((s, i) => (
                      <div key={i} className="ai-suggestion">
                        <div className="ai-suggestion-top">
                          <span className={`ai-suggestion-type ai-sug-${s.type}`}>{s.type.replace('_', ' ')}</span>
                          <span className="ai-suggestion-savings">€{s.savings.toLocaleString()} savings</span>
                          <span className={`ai-suggestion-risk risk-${s.risk}`}>{s.risk} risk</span>
                          <ReliabilityBadge score={s.reliability} />
                        </div>
                        <div className="ai-suggestion-title">{s.title}</div>
                        <div className="ai-suggestion-desc">{s.description}</div>
                      </div>
                    ))}
                    <div className="ai-card-total">Total potential savings: €{(msg.budgetSuggestions as BudgetSuggestion[]).reduce((s, x) => s + x.savings, 0).toLocaleString()}</div>
                  </div>
                ) : null}

                {/* Anomaly reports */}
                {(msg.anomalies as AnomalyReport[] | undefined)?.length ? (
                  <div className="ai-card ai-card-anomaly">
                    <div className="ai-card-header"><span className="ai-card-icon">!</span>Anomaly Detection</div>
                    {(msg.anomalies as AnomalyReport[]).map((a, i) => (
                      <div key={i} className={`ai-anomaly ai-anomaly-${a.severity}`}>
                        <div className="ai-anomaly-top">
                          <span className="ai-anomaly-loc">{a.locationName}</span>
                          <span className={`ai-anomaly-sev sev-${a.severity}`}>{a.severity}</span>
                          <ReliabilityBadge score={a.reliability} />
                        </div>
                        <div className="ai-anomaly-param">{a.parameter}: <strong>{a.currentValue}</strong> (avg: {a.historicalAvg}, threshold: {a.threshold})</div>
                        <div className="ai-anomaly-rec">{a.recommendation}</div>
                      </div>
                    ))}
                  </div>
                ) : null}

                {/* Generated report */}
                {msg.report ? (() => {
                  const r = msg.report as GeneratedReport;
                  return (
                    <div className="ai-card ai-card-report">
                      <div className="ai-card-header">
                        <span className="ai-card-icon">D</span>
                        {r.title}
                        <ReliabilityBadge score={r.reliability} />
                        <button className="ai-report-pdf" onClick={() => exportReportToPdf(r)} title="Export as PDF">
                          <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M14 2H6a2 2 0 00-2 2v16a2 2 0 002 2h12a2 2 0 002-2V8z"/><polyline points="14 2 14 8 20 8"/><line x1="16" y1="13" x2="8" y2="13"/><line x1="16" y1="17" x2="8" y2="17"/><polyline points="10 9 9 9 8 9"/></svg>
                          PDF
                        </button>
                      </div>
                      <div className="ai-report-period">{r.period}</div>
                      {r.metrics && Object.keys(r.metrics).length > 0 && (
                        <div className="ai-report-metrics">
                          {Object.entries(r.metrics).map(([k, v]) => (
                            <div key={k} className="ai-report-metric"><span className="ai-report-metric-label">{k}</span><span className="ai-report-metric-val">{v}</span></div>
                          ))}
                        </div>
                      )}
                      {r.sections.map((s, i) => (
                        <div key={i} className="ai-report-section">
                          <div className="ai-report-heading">{s.heading}</div>
                          <div className="ai-report-content">{s.content}</div>
                        </div>
                      ))}
                    </div>
                  );
                })() : null}

                {/* Field notes interpretation */}
                {msg.fieldNotes ? (() => {
                  const fn = msg.fieldNotes as FieldNotesResult;
                  return (
                    <div className="ai-card ai-card-fieldnotes">
                      <div className="ai-card-header"><span className="ai-card-icon">N</span>Structured Field Notes<ReliabilityBadge score={fn.reliability} /></div>
                      <div className="ai-fn-grid">
                        {fn.visual_observation && <div className="ai-fn-field"><span className="ai-fn-label">Visual</span><span>{fn.visual_observation}</span></div>}
                        {fn.odor && fn.odor !== 'none' && <div className="ai-fn-field"><span className="ai-fn-label">Odor</span><span>{fn.odor}</span></div>}
                        {fn.sample_time && fn.sample_time !== 'unknown' && <div className="ai-fn-field"><span className="ai-fn-label">Sample time</span><span>{fn.sample_time}</span></div>}
                        {fn.flow_condition && <div className="ai-fn-field"><span className="ai-fn-label">Flow</span><span>{fn.flow_condition}</span></div>}
                        {fn.weather && fn.weather !== 'unknown' && <div className="ai-fn-field"><span className="ai-fn-label">Weather</span><span>{fn.weather}</span></div>}
                      </div>
                      {fn.flags.length > 0 && (
                        <div className="ai-fn-flags">
                          {fn.flags.map((f, i) => <span key={i} className="ai-fn-flag">{f}</span>)}
                        </div>
                      )}
                    </div>
                  );
                })() : null}
                {msg.role === 'assistant' && msg.actions && msg.actions.length > 0 && (
                  <div className="chat-actions">
                    {msg.actions.map((action) => (
                      <ActionButton
                        key={action.id}
                        action={action}
                        isOpen={openDropdown === action.id}
                        disabled={isTyping}
                        onClick={() => handleActionClick(action)}
                        onOptionClick={(prompt) => sendActionPrompt(prompt)}
                      />
                    ))}
                  </div>
                )}
              </div>
              );
            })}
            {isTyping && (
              <div className="typing-indicator">
                <div className="typing-dots">
                  <span></span>
                  <span></span>
                  <span></span>
                </div>
                Thinking...
              </div>
            )}
          </div>
        )}

        {/* Quick Actions */}
        <div className="quick-actions">
          {quickActions.map((action) => (
            <button
              key={action.title}
              className="qa-card"
              onClick={() => handleQuickAction(action.prompt)}
            >
              <div className="qa-label">{action.title}</div>
              <div className="qa-desc">{action.description}</div>
            </button>
          ))}
        </div>

        {/* Overview Stats */}
        <div className="section-label">{isLabWorker ? 'Your lab overview' : isFieldWorker ? 'Your field work' : 'Your overview'}</div>
        {isLabWorker ? (
          <div className="stats-row">
            <div className="stat-card">
              <div className="stat-label">In Transit</div>
              <div className="stat-val" style={{ color: '#BA7517' }}>{labInTransit}</div>
              <div className="stat-sub">Arriving soon</div>
            </div>
            <div className="stat-card">
              <div className="stat-label">In Lab</div>
              <div className="stat-val" style={{ color: '#D97706' }}>{labInLab}</div>
              <div className="stat-sub stat-warn">Ready to analyze</div>
            </div>
            <div className="stat-card">
              <div className="stat-label">Analyzed</div>
              <div className="stat-val" style={{ color: '#059669' }}>{labAnalyzed}</div>
              <div className="stat-sub">Awaiting validation</div>
            </div>
            <div className="stat-card">
              <div className="stat-label">Total assigned</div>
              <div className="stat-val">{labTotal}</div>
              <div className="stat-sub">All samples</div>
            </div>
          </div>
        ) : isFieldWorker ? (
          <div className="stats-row stats-row-3">
            <div className="stat-card">
              <div className="stat-label">Assigned visits</div>
              <div className="stat-val">{myVisitsTotal}</div>
              <div className="stat-sub stat-warn">{myVisitsPending} pending</div>
            </div>
            <div className="stat-card">
              <div className="stat-label">Measurements</div>
              <div className="stat-val">{myMeasurementsCount}</div>
              <div className="stat-sub">Total assigned</div>
            </div>
            <div className="stat-card">
              <div className="stat-label">Alerts</div>
              <div className="stat-val stat-bad">{dashboardStats.anomalyCount}</div>
              <div className="stat-sub stat-bad">{dashboardStats.anomalyCount} anomaly</div>
            </div>
          </div>
        ) : (
          <div className="stats-row">
            <div className="stat-card">
              <div className="stat-label">Active plans</div>
              <div className="stat-val">{monitoringPlans.filter(p => p.status === 'active').length}</div>
              <div className={`stat-sub ${monitoringPlans.some(p => p.status === 'active') ? 'stat-good' : ''}`}>
                {monitoringPlans.filter(p => p.status === 'active').length > 0
                  ? `${monitoringPlans.filter(p => p.status === 'draft').length} draft`
                  : 'No active plans'}
              </div>
            </div>
            <div className="stat-card">
              <div className="stat-label">Visits this month</div>
              <div className="stat-val">{visits.filter(v => v.planned_date >= '2026-03-01' && v.planned_date <= '2026-03-31').length}</div>
              <div className="stat-sub stat-warn">{visits.filter(v => v.planned_date >= '2026-03-01' && v.planned_date <= '2026-03-31' && v.status === 'planned').length} pending</div>
            </div>
            <div className="stat-card">
              <div className="stat-label">Budget used</div>
              <div className="stat-val">{budgetPercent}%</div>
              <div className={`stat-sub ${budgetPercent > 80 ? 'stat-warn' : budgetPercent > 100 ? 'stat-bad' : 'stat-good'}`}>
                {budgetPercent <= 25 ? 'Q1 on target' : budgetPercent <= 50 ? 'Q2 on target' : budgetPercent <= 75 ? 'Q3 on target' : budgetPercent <= 100 ? 'Near limit' : 'Over budget'}
              </div>
            </div>
            <div className="stat-card">
              <div className="stat-label">Alerts</div>
              <div className="stat-val stat-bad">{measurements.filter(m => m.pipeline_status === 'rejected').length + activityItems.filter(a => a.hasAnomaly).length}</div>
              <div className="stat-sub stat-bad">
                {activityItems.filter(a => a.hasAnomaly).length} anomal{activityItems.filter(a => a.hasAnomaly).length === 1 ? 'y' : 'ies'}
                {measurements.filter(m => m.pipeline_status === 'rejected').length > 0 && `, ${measurements.filter(m => m.pipeline_status === 'rejected').length} rejected`}
              </div>
            </div>
          </div>
        )}

        {/* Upcoming Tasks / Lab Samples */}
        <div className="section-label">{isLabWorker ? 'Samples needing analysis' : isFieldWorker ? 'Your upcoming visits' : 'Upcoming tasks'}</div>
        {isLabWorker ? (
          <div className="tasks-list">
            {labSamples.filter(m => m.pipeline_status === 'in_lab' || m.pipeline_status === 'in_transit').length === 0 ? (
              <div style={{ textAlign: 'center', padding: '1.5rem', color: 'var(--color-text-secondary)', fontSize: '13px' }}>
                No samples currently waiting for analysis.
              </div>
            ) : (
              labSamples
                .filter(m => m.pipeline_status === 'in_lab' || m.pipeline_status === 'in_transit')
                .map(m => {
                  const loc = locations.find(l => l.id === m.location_id);
                  const tmpl = measurementTemplates.find(t => t.id === m.measurement_template_id);
                  const collector = users.find(u => u.id === (m.recorded_by || m.assignee_id));
                  const isInLab = m.pipeline_status === 'in_lab';
                  return (
                    <div key={m.id} className="task-item">
                      <div className={`task-dot ${isInLab ? 'dot-today' : 'dot-planned'}`}></div>
                      <div className="task-info">
                        <div className="task-title">{tmpl?.name ?? 'Unknown'} — {loc?.name ?? 'Unknown'}</div>
                        <div className="task-meta">
                          Collected by {collector?.full_name ?? '—'} &middot; {formatDate(m.measurement_date || m.planned_date)}
                        </div>
                      </div>
                      <span className={`task-badge ${isInLab ? 'badge-today' : 'badge-upcoming'}`}>
                        {isInLab ? 'In Lab' : 'In Transit'}
                      </span>
                    </div>
                  );
                })
            )}
          </div>
        ) : (
          <div className="tasks-list">
            {upcomingTasks.length === 0 ? (
              <div style={{ textAlign: 'center', padding: '1.5rem', color: 'var(--color-text-secondary)', fontSize: '13px' }}>
                No upcoming tasks assigned to you.
              </div>
            ) : (
              upcomingTasks.map((task) => (
                <div key={task.id} className="task-item">
                  <div className={`task-dot ${task.dotClass}`}></div>
                  <div className="task-info">
                    <div className="task-title">{task.name}</div>
                    <div className="task-meta">
                      {task.measurementType}
                      {!isFieldWorker && <> &middot; {task.assignee}</>}
                      {' '}&middot; {formatDate(task.date)}
                    </div>
                  </div>
                  <span className={`task-badge ${task.badgeClass}`}>{task.badgeLabel}</span>
                </div>
              ))
            )}
          </div>
        )}
      </div>
    </>
  );
}

/* ---- Chat Card Renderer ---- */

function ChatCardRenderer({ card }: { card: ChatCard }) {
  if (card.type === 'plan_preview') {
    const d = card.data as {
      locations: string[];
      measurements: string[];
      estimatedBudget: string;
      frequency: string;
    };
    return (
      <div className="chat-card">
        <div className="chat-card-title">{card.title}</div>
        <div className="chat-card-grid">
          <div>
            <div className="chat-card-item-label">Locations</div>
            <ul className="chat-card-list">
              {d.locations.map((l) => (
                <li key={l}>{l}</li>
              ))}
            </ul>
          </div>
          <div>
            <div className="chat-card-item-label">Measurements</div>
            <ul className="chat-card-list">
              {d.measurements.map((m) => (
                <li key={m}>{m}</li>
              ))}
            </ul>
          </div>
        </div>
        <div className="chat-card-footer">
          <span>Budget: <strong>{d.estimatedBudget}</strong></span>
          <span>Frequency: <strong>{d.frequency}</strong></span>
        </div>
      </div>
    );
  }

  if (card.type === 'stats') {
    const d = card.data as Record<string, string | number>;
    return (
      <div className="chat-card">
        <div className="chat-card-title">{card.title}</div>
        <div className="chat-card-grid">
          {Object.entries(d).map(([key, val]) => (
            <div key={key}>
              <div className="chat-card-item-label">
                {key.replace(/([A-Z])/g, ' $1').trim()}
              </div>
              <div className="chat-card-item-value">{val}</div>
            </div>
          ))}
        </div>
      </div>
    );
  }

  if (card.type === 'table') {
    const d = card.data as Record<string, string | number>[];
    if (!d.length) return null;
    const keys = Object.keys(d[0]);
    return (
      <div className="chat-card">
        <div className="chat-card-title">{card.title}</div>
        <table className="chat-card-table">
          <thead>
            <tr>
              {keys.map((k) => (
                <th key={k}>{k}</th>
              ))}
            </tr>
          </thead>
          <tbody>
            {d.map((row, i) => (
              <tr key={i}>
                {keys.map((k) => (
                  <td key={k}>{row[k]}</td>
                ))}
              </tr>
            ))}
          </tbody>
        </table>
      </div>
    );
  }

  if (card.type === 'suggestions') {
    const d = card.data as string[];
    return (
      <div className="chat-card">
        <div className="chat-card-title">{card.title}</div>
        <ul className="chat-card-list chat-card-suggestions">
          {d.map((item, i) => (
            <li key={i}>{item}</li>
          ))}
        </ul>
      </div>
    );
  }

  return null;
}

/* ---- Action Icon SVGs ---- */

const actionIcons: Record<ChatAction['icon'], string> = {
  generate: 'M19 8l-4 4h3c0 3.31-2.69 6-6 6a5.87 5.87 0 01-2.8-.7l-1.46 1.46A7.93 7.93 0 0012 20c4.42 0 8-3.58 8-8h3l-4-4zM6 12c0-3.31 2.69-6 6-6 1.01 0 1.97.25 2.8.7l1.46-1.46A7.93 7.93 0 0012 4c-4.42 0-8 3.58-8 8H1l4 4 4-4H6z',
  assign: 'M12 12c2.21 0 4-1.79 4-4s-1.79-4-4-4-4 1.79-4 4 1.79 4 4 4zm0 2c-2.67 0-8 1.34-8 4v2h16v-2c0-2.66-5.33-4-8-4z',
  edit: 'M3 17.25V21h3.75L17.81 9.94l-3.75-3.75L3 17.25zM20.71 7.04a1 1 0 000-1.41l-2.34-2.34a1 1 0 00-1.41 0l-1.83 1.83 3.75 3.75 1.83-1.83z',
  approve: 'M9 16.17L4.83 12l-1.42 1.41L9 19 21 7l-1.41-1.41L9 16.17z',
  schedule: 'M19 3h-1V1h-2v2H8V1H6v2H5c-1.11 0-2 .9-2 2v14c0 1.1.89 2 2 2h14c1.1 0 2-.9 2-2V5c0-1.1-.9-2-2-2zm0 16H5V8h14v11zM9 10H7v2h2v-2zm4 0h-2v2h2v-2zm4 0h-2v2h2v-2z',
  budget: 'M11.8 10.9c-2.27-.59-3-1.2-3-2.15 0-1.09 1.01-1.85 2.7-1.85 1.78 0 2.44.85 2.5 2.1h2.21c-.07-1.72-1.12-3.3-3.21-3.81V3h-3v2.16c-1.94.42-3.5 1.68-3.5 3.61 0 2.31 1.91 3.46 4.7 4.13 2.5.6 3 1.48 3 2.41 0 .69-.49 1.79-2.7 1.79-2.06 0-2.87-.92-2.98-2.1h-2.2c.12 2.19 1.76 3.42 3.68 3.83V21h3v-2.15c1.95-.37 3.5-1.5 3.5-3.55 0-2.84-2.43-3.81-4.7-4.4z',
  view: 'M12 4.5C7 4.5 2.73 7.61 1 12c1.73 4.39 6 7.5 11 7.5s9.27-3.11 11-7.5c-1.73-4.39-6-7.5-11-7.5zM12 17c-2.76 0-5-2.24-5-5s2.24-5 5-5 5 2.24 5 5-2.24 5-5 5zm0-8c-1.66 0-3 1.34-3 3s1.34 3 3 3 3-1.34 3-3-1.34-3-3-3z',
};

/* ---- Action Button Component ---- */

function ActionButton({
  action,
  isOpen,
  disabled,
  onClick,
  onOptionClick,
}: {
  action: ChatAction;
  isOpen: boolean;
  disabled: boolean;
  onClick: () => void;
  onOptionClick: (prompt: string) => void;
}) {
  if (action.type === 'dropdown' && action.options) {
    return (
      <div className="chat-action-dropdown">
        <button className="chat-action-btn" onClick={(e) => { e.stopPropagation(); onClick(); }} disabled={disabled}>
          <svg viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg">
            <path d={actionIcons[action.icon]} fill="currentColor" />
          </svg>
          {action.label}
          <svg className={`chat-action-chevron${isOpen ? ' open' : ''}`} viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg">
            <path d="M7 10l5 5 5-5z" fill="currentColor" />
          </svg>
        </button>
        {isOpen && (
          <div className="chat-dropdown-menu">
            {action.options.map((opt) => (
              <button
                key={opt.value}
                className="chat-dropdown-item"
                onClick={() => onOptionClick(opt.prompt)}
              >
                {opt.label}
              </button>
            ))}
          </div>
        )}
      </div>
    );
  }

  return (
    <button className="chat-action-btn" onClick={onClick} disabled={disabled}>
      <svg viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg">
        <path d={actionIcons[action.icon]} fill="currentColor" />
      </svg>
      {action.label}
    </button>
  );
}
